"""
Permata USD savings statement parser.

Observed statement shape:
  - One-page "Mutasi Transaksi" PDF generated by a custom frontend (react-pdf)
  - Header includes:
      "Mutasi Transaksi"
      "Periode <Bulan> <YYYY>"
      "Dollar iB - Mudharabah"
      "0098-0933-8298"
  - Transactions are grouped below a full date row:
      01 Januari 2026
      PB Pajak Bagi Hasil                     USD 0.10
      PB Bagi Hasil                           USD 0.48

The PDF does not embed a running balance column, so this parser reconstructs
it from a known opening balance and prior monthly statement closings.

FX rule:
  - Never hardcode USD/IDR
  - Resolve the rate from the paired Permata IDR statement for the same month:
      Permata_Helen_<MM>_<YYYY>.pdf
  - If the paired statement yields zero or multiple distinct USD→IDR rates,
    stop with a clear error so the operator can choose the source explicitly.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path
import calendar
import re
from typing import Optional

import pdfplumber

from parsers.base import AccountSummary, StatementResult, Transaction


MONTHS_ID = {
    "JANUARI": 1,
    "FEBRUARI": 2,
    "MARET": 3,
    "APRIL": 4,
    "MEI": 5,
    "JUNI": 6,
    "JULI": 7,
    "AGUSTUS": 8,
    "SEPTEMBER": 9,
    "OKTOBER": 10,
    "NOVEMBER": 11,
    "DESEMBER": 12,
}

ACCOUNT_NUMBER = "9809338298"
ACCOUNT_NUMBER_DISPLAY = "0098-0933-8298"
PRODUCT_NAME = "Dollar iB - Mudharabah"
OWNER = "Helen"

# User-provided seed so the first monthly closing can be reconstructed.
OPENING_BALANCE_SEEDS: dict[tuple[str, int, int], float] = {
    (ACCOUNT_NUMBER, 2026, 1): 8323.71,
}

_PAIR_IDR_NAME = re.compile(r"^Permata_Helen_USD_(\d{2})_(\d{4})\.pdf$")
_PERIOD_RE = re.compile(r"Periode\s+([A-Za-z]+)\s+(\d{4})", re.IGNORECASE)
_DATE_ROW_RE = re.compile(r"^(\d{2})\s+([A-Za-z]+)\s+(\d{4})$", re.IGNORECASE)
_BOND_USD_RATE_RE = re.compile(
    r"^.+?\s+USD\s+[\d,]+\.\d{2}\s+[\d.,]+\s+([\d,]+\.\d{2})\s+([\d,]+\.\d{2})\s+-?[\d,]+\.\d{2}\s+-?[\d.,]+%\s*$"
)

_CLOSING_CACHE: dict[Path, float] = {}


@dataclass
class _StatementRow:
    tx_date: str
    description: str
    foreign_amount: float
    tx_type: str

    @property
    def signed_amount(self) -> float:
        return -self.foreign_amount if self.tx_type == "Debit" else self.foreign_amount


def can_parse(text_page1: str) -> bool:
    return "Mutasi Transaksi" in text_page1 and PRODUCT_NAME in text_page1


def parse(
    pdf_path: str,
    owner_mappings: dict[str, str] | None = None,
    ollama_client=None,
) -> StatementResult:
    path = Path(pdf_path)
    period_start, period_end, rows = _extract_statement_rows(path)
    exchange_rate = extract_same_month_idr_exchange_rate(path)
    opening_balance = _resolve_opening_balance(path, ACCOUNT_NUMBER, period_start)

    transactions: list[Transaction] = []
    running_balance = opening_balance
    total_debit = 0.0
    total_credit = 0.0

    for row in rows:
        running_balance = round(running_balance + row.signed_amount, 2)
        amount_idr = round(row.signed_amount * exchange_rate, 2)
        if row.tx_type == "Debit":
            total_debit += row.foreign_amount
        else:
            total_credit += row.foreign_amount

        transactions.append(Transaction(
            date_transaction=row.tx_date,
            date_posted=None,
            description=row.description,
            currency="USD",
            foreign_amount=row.foreign_amount,
            exchange_rate=exchange_rate,
            amount_idr=amount_idr,
            tx_type=row.tx_type,
            balance=running_balance,
            account_number=ACCOUNT_NUMBER,
            owner=OWNER,
        ))

    closing_balance = round(running_balance, 2)
    summary = AccountSummary(
        product_name=PRODUCT_NAME,
        account_number=ACCOUNT_NUMBER,
        currency="USD",
        closing_balance=closing_balance,
        opening_balance=opening_balance,
        total_debit=round(total_debit, 2),
        total_credit=round(total_credit, 2),
        closing_balance_idr=round(closing_balance * exchange_rate, 2),
        period_start=_date_to_str(period_start),
        period_end=_date_to_str(period_end),
    )

    month_label = period_end.strftime("%b %Y")
    return StatementResult(
        bank="Permata",
        statement_type="savings",
        owner=OWNER,
        sheet_name=f"{month_label} Savings",
        transactions=transactions,
        summary=summary,
        accounts=[summary],
        customer_name="DR DIAN PRATIWI",
        period_start=_date_to_str(period_start) or "",
        period_end=_date_to_str(period_end) or "",
        exchange_rates={"USD": exchange_rate},
    )


def extract_same_month_idr_exchange_rate(usd_pdf_path: str | Path) -> float:
    """
    Return the unique USD→IDR rate embedded in the paired same-month IDR statement.

    The counterpart must follow the exact repository naming convention:
      Permata_Helen_USD_MM_YYYY.pdf  ->  Permata_Helen_MM_YYYY.pdf
    """
    usd_path = Path(usd_pdf_path)
    m = _PAIR_IDR_NAME.match(usd_path.name)
    if not m:
        raise ValueError(
            f"Cannot derive paired IDR statement from filename: {usd_path.name}. "
            "Expected Permata_Helen_USD_MM_YYYY.pdf"
        )

    mm, yyyy = m.groups()
    idr_path = usd_path.with_name(f"Permata_Helen_{mm}_{yyyy}.pdf")
    if not idr_path.exists():
        raise ValueError(
            f"No paired Permata IDR statement found for {mm}/{yyyy}: {idr_path.name}. "
            "Add the same-month IDR statement, then retry."
        )

    with pdfplumber.open(str(idr_path)) as pdf:
        all_text = "\n".join((page.extract_text() or "") for page in pdf.pages)

    rates: set[float] = set()
    for line in all_text.splitlines():
        line_s = line.strip()
        if "USD" not in line_s:
            continue
        match = _BOND_USD_RATE_RE.match(line_s)
        if not match:
            continue
        market_value_usd = _parse_usd_amount(match.group(1))
        market_value_idr = _parse_usd_amount(match.group(2))
        if market_value_usd <= 0 or market_value_idr <= 0:
            continue
        rates.add(round(market_value_idr / market_value_usd, 6))

    if not rates:
        raise ValueError(
            f"No USD→IDR rate found in paired Permata IDR statement {idr_path.name}. "
            "Please confirm the intended reference file."
        )
    if len(rates) > 1:
        raise ValueError(
            f"Multiple USD→IDR rates found in paired Permata IDR statement {idr_path.name}: "
            f"{sorted(rates)}. Please clarify which one to use."
        )
    return next(iter(rates))


def _extract_statement_rows(pdf_path: Path) -> tuple[date, date, list[_StatementRow]]:
    with pdfplumber.open(str(pdf_path)) as pdf:
        if not pdf.pages:
            raise ValueError(f"Empty PDF: {pdf_path.name}")
        page = pdf.pages[0]
        text = page.extract_text() or ""
        words = page.extract_words(use_text_flow=True, keep_blank_chars=False)

    period_start, period_end = _parse_period(text)
    rows = _group_words_into_rows(words)

    transactions: list[_StatementRow] = []
    current_date: Optional[str] = None

    for row in rows:
        row_text = " ".join(token["text"] for token in row).strip()
        if not row_text:
            continue

        date_match = _DATE_ROW_RE.match(row_text)
        if date_match:
            current_date = _parse_date_row(date_match)
            continue

        txn = _parse_transaction_row(row, current_date)
        if txn is not None:
            transactions.append(txn)

    if not transactions:
        raise ValueError(
            f"No transaction rows found in {pdf_path.name}. "
            "The Permata USD statement format may have changed."
        )

    return period_start, period_end, transactions


def _parse_period(text: str) -> tuple[date, date]:
    m = _PERIOD_RE.search(text)
    if not m:
        raise ValueError("Could not find 'Periode <Bulan> <YYYY>' in Permata USD PDF")

    month_name, year_raw = m.groups()
    month = MONTHS_ID.get(month_name.upper())
    if not month:
        raise ValueError(f"Unknown month in Permata USD period header: {month_name}")

    year = int(year_raw)
    last_day = calendar.monthrange(year, month)[1]
    return date(year, month, 1), date(year, month, last_day)


def _group_words_into_rows(words: list[dict], tolerance: float = 3.0) -> list[list[dict]]:
    rows: list[list[dict]] = []
    for word in sorted(words, key=lambda w: (w["top"], w["x0"])):
        if not rows or abs(rows[-1][0]["top"] - word["top"]) > tolerance:
            rows.append([word])
        else:
            rows[-1].append(word)
    return [sorted(row, key=lambda w: w["x0"]) for row in rows]


def _parse_date_row(match: re.Match[str]) -> str:
    day_raw, month_name, year_raw = match.groups()
    month = MONTHS_ID.get(month_name.upper())
    if not month:
        raise ValueError(f"Unknown month in transaction date row: {month_name}")
    return f"{int(day_raw):02d}/{month:02d}/{int(year_raw):04d}"


def _parse_transaction_row(row: list[dict], current_date: Optional[str]) -> Optional[_StatementRow]:
    if current_date is None:
        return None

    amount_tokens = [token for token in row if token["x0"] >= 1000]
    if len(amount_tokens) < 2:
        return None

    if amount_tokens[0]["text"] != "USD":
        return None

    amount = _parse_usd_amount(amount_tokens[1]["text"])
    desc_tokens = [token["text"] for token in row if 100 <= token["x0"] < 1000]
    description = " ".join(desc_tokens).strip()
    if not description:
        raise ValueError("Encountered USD amount row without a description")

    tx_type = _infer_tx_type(description)
    return _StatementRow(
        tx_date=current_date,
        description=description,
        foreign_amount=amount,
        tx_type=tx_type,
    )


def _infer_tx_type(description: str) -> str:
    desc = description.upper()
    if "PAJAK" in desc or "BIAYA" in desc or "ADMIN" in desc:
        return "Debit"
    if "BAGI HASIL" in desc:
        return "Credit"
    raise ValueError(
        f"Cannot determine Debit/Credit for Permata USD transaction: {description!r}. "
        "The PDF format may have changed."
    )


def _resolve_opening_balance(pdf_path: Path, account_number: str, period_start: date) -> float:
    seed_key = (account_number, period_start.year, period_start.month)
    if seed_key in OPENING_BALANCE_SEEDS:
        return OPENING_BALANCE_SEEDS[seed_key]

    prev_year, prev_month = _previous_month(period_start.year, period_start.month)
    prev_path = pdf_path.with_name(f"Permata_Helen_USD_{prev_month:02d}_{prev_year}.pdf")
    if not prev_path.exists():
        raise ValueError(
            f"No opening balance seed or previous Permata USD statement found for "
            f"{period_start.strftime('%b %Y')} ({prev_path.name})."
        )
    return _resolve_closing_balance(prev_path)


def _resolve_closing_balance(pdf_path: Path) -> float:
    cached = _CLOSING_CACHE.get(pdf_path)
    if cached is not None:
        return cached

    period_start, _period_end, rows = _extract_statement_rows(pdf_path)
    opening_balance = _resolve_opening_balance(pdf_path, ACCOUNT_NUMBER, period_start)
    closing_balance = round(opening_balance + sum(row.signed_amount for row in rows), 2)
    _CLOSING_CACHE[pdf_path] = closing_balance
    return closing_balance


def _previous_month(year: int, month: int) -> tuple[int, int]:
    if month == 1:
        return year - 1, 12
    return year, month - 1


def _parse_usd_amount(value: str) -> float:
    return float(value.replace(",", ""))


def _date_to_str(d: Optional[date]) -> Optional[str]:
    if d is None:
        return None
    return f"{d.day:02d}/{d.month:02d}/{d.year}"
